#!/bin/bash
#set -ex

IDEAL=~/Github/binary-decompilation/x86-semantics/docs/relatedwork/k-semantics/current_support.txt


grep "^adc[blwq]*_" $IDEAL
grep "^add[blwq]*_" $IDEAL
grep "^addpd[blwq]*_" $IDEAL
grep "^addps[blwq]*_" $IDEAL
grep "^addsd[blwq]*_" $IDEAL
grep "^addss[blwq]*_" $IDEAL
grep "^addsubpd[blwq]*_" $IDEAL
grep "^addsubps[blwq]*_" $IDEAL
grep "^and[blwq]*_" $IDEAL
grep "^andn[blwq]*_" $IDEAL
grep "^andnpd[blwq]*_" $IDEAL
grep "^andnps[blwq]*_" $IDEAL
grep "^andpd[blwq]*_" $IDEAL
grep "^andps[blwq]*_" $IDEAL
grep "^blsi[blwq]*_" $IDEAL
grep "^blsr[blwq]*_" $IDEAL
grep "^bswap[blwq]*_" $IDEAL
grep "^bt[blwq]*_" $IDEAL
grep "^cbw[blwq]*_" $IDEAL
grep "^cdqe[blwq]*_" $IDEAL
grep "^cbtw" $IDEAL
grep "^clc" $IDEAL
grep "^cltd" $IDEAL
grep "^cltq" $IDEAL
grep "^cmc" $IDEAL
grep "^cwtd" $IDEAL
grep "^cwtl" $IDEAL
grep "^cld" $IDEAL
grep "^cqto" $IDEAL
grep "^cmova[blwq]*_" $IDEAL
grep "^cmovae[blwq]*_" $IDEAL
grep "^cmovb[blwq]*_" $IDEAL
grep "^cmovbe[blwq]*_" $IDEAL
grep "^cmovc[blwq]*_" $IDEAL
grep "^cmove[blwq]*_" $IDEAL
grep "^cmovg[blwq]*_" $IDEAL
grep "^cmovge[blwq]*_" $IDEAL
grep "^cmovl[blwq]*_" $IDEAL
grep "^cmovle[blwq]*_" $IDEAL
grep "^cmovna[blwq]*_" $IDEAL
grep "^cmovnae[blwq]*_" $IDEAL
grep "^cmovnb[blwq]*_" $IDEAL
grep "^cmovnc[blwq]*_" $IDEAL
grep "^cmovne[blwq]*_" $IDEAL
grep "^cmovng[blwq]*_" $IDEAL
grep "^cmovnge[blwq]*_" $IDEAL
grep "^cmovnl[blwq]*_" $IDEAL
grep "^cmovnle[blwq]*_" $IDEAL
grep "^cmovno[blwq]*_" $IDEAL
grep "^cmovnp[blwq]*_" $IDEAL
grep "^cmovns[blwq]*_" $IDEAL
grep "^cmovnz[blwq]*_" $IDEAL
grep "^cmovo[blwq]*_" $IDEAL
grep "^cmovp[blwq]*_" $IDEAL
grep "^cmovpo[blwq]*_" $IDEAL
grep "^cmovs[blwq]*_" $IDEAL
grep "^cmovz[blwq]*_" $IDEAL
grep "^cmp[blwq]*_" $IDEAL
grep "^cmpxchg[blwq]*_" $IDEAL
grep "^cqo[blwq]*_" $IDEAL
grep "^cvtdq2pd[blwq]*_" $IDEAL
grep "^cvtdq2ps[blwq]*_" $IDEAL
grep "^cvtpd2dq[blwq]*_" $IDEAL
grep "^cvtpd2ps[blwq]*_" $IDEAL
grep "^cvtps2dq[blwq]*_" $IDEAL
grep "^cvtps2pd[blwq]*_" $IDEAL
grep "^cvtsd2si[blwq]*_" $IDEAL
grep "^cvtsi2sd[blwq]*_" $IDEAL
grep "^cvtsi2ss[blwq]*_" $IDEAL
grep "^cvtss2si[blwq]*_" $IDEAL
grep "^cvttpd2dq[blwq]*_" $IDEAL
grep "^cvttps2dq[blwq]*_" $IDEAL
grep "^cvttsd2si[blwq]*_" $IDEAL
grep "^cvttss2si[blwq]*_" $IDEAL
grep "^cwd[blwq]*_" $IDEAL
grep "^cwde[blwq]*_" $IDEAL
grep "^dec[blwq]*_" $IDEAL
grep "^divpd[blwq]*_" $IDEAL
grep "^divps[blwq]*_" $IDEAL
grep "^divsd[blwq]*_" $IDEAL
grep "^divss[blwq]*_" $IDEAL
grep "^haddpd[blwq]*_" $IDEAL
grep "^haddps[blwq]*_" $IDEAL
grep "^hsubpd[blwq]*_" $IDEAL
grep "^hsubps[blwq]*_" $IDEAL
grep "^inc[blwq]*_" $IDEAL
grep "^maxpd[blwq]*_" $IDEAL
grep "^maxps[blwq]*_" $IDEAL
grep "^maxsd[blwq]*_" $IDEAL
grep "^maxss[blwq]*_" $IDEAL
grep "^minpd[blwq]*_" $IDEAL
grep "^minps[blwq]*_" $IDEAL
grep "^minsd[blwq]*_" $IDEAL
grep "^minss[blwq]*_" $IDEAL
grep "^mov[blwq]*_" $IDEAL
grep "^movd[blwq]*_" $IDEAL
grep "^movhlps[blwq]*_" $IDEAL
grep "^movmskpd[blwq]*_" $IDEAL
grep "^movmskps[blwq]*_" $IDEAL
grep "^movq[blwq]*_" $IDEAL
grep "^movshdup[blwq]*_" $IDEAL
grep "^movsldup[blwq]*_" $IDEAL
grep "^movsxd[blwq]*_" $IDEAL
grep "^movzx[blwq]*_" $IDEAL
grep "^mulpd[blwq]*_" $IDEAL
grep "^mulps[blwq]*_" $IDEAL
grep "^mulsd[blwq]*_" $IDEAL
grep "^mulss[blwq]*_" $IDEAL
grep "^neg[blwq]*_" $IDEAL
grep "^nop[blwq]*_" $IDEAL
grep "^not[blwq]*_" $IDEAL
grep "^or[blwq]*_" $IDEAL
grep "^orpd[blwq]*_" $IDEAL
grep "^orps[blwq]*_" $IDEAL
grep "^paddd[blwq]*_" $IDEAL
grep "^paddq[blwq]*_" $IDEAL
grep "^pand[blwq]*_" $IDEAL
grep "^pandn[blwq]*_" $IDEAL
grep "^phaddd[blwq]*_" $IDEAL
grep "^phsubd[blwq]*_" $IDEAL
grep "^pmovsxbd[blwq]*_" $IDEAL
grep "^pmovsxbq[blwq]*_" $IDEAL
grep "^pmovsxdq[blwq]*_" $IDEAL
grep "^pmovsxwd[blwq]*_" $IDEAL
grep "^pmovsxwq[blwq]*_" $IDEAL
grep "^pmovzxbd[blwq]*_" $IDEAL
grep "^pmovzxdq[blwq]*_" $IDEAL
grep "^pmovzxwq[blwq]*_" $IDEAL
grep "^popcnt[blwq]*_" $IDEAL
grep "^por[blwq]*_" $IDEAL
grep "^psubd[blwq]*_" $IDEAL
grep "^psubq[blwq]*_" $IDEAL
grep "^punpckhdq[blwq]*_" $IDEAL
grep "^punpckhqdq[blwq]*_" $IDEAL
grep "^punpckhwd[blwq]*_" $IDEAL
grep "^punpckldq[blwq]*_" $IDEAL
grep "^punpcklqdq[blwq]*_" $IDEAL
grep "^punpcklwd[blwq]*_" $IDEAL
grep "^pxor[blwq]*_" $IDEAL
grep "^rcl[blwq]*_" $IDEAL
grep "^rcpps[blwq]*_" $IDEAL
grep "^rcpss[blwq]*_" $IDEAL
grep "^rol[blwq]*_" $IDEAL
grep "^ror[blwq]*_" $IDEAL
grep "^rsqrtps[blwq]*_" $IDEAL
grep "^rsqrtss[blwq]*_" $IDEAL
grep "^sal[blwq]*_" $IDEAL
grep "^sar[blwq]*_" $IDEAL
grep "^sarx[blwq]*_" $IDEAL
grep "^sbb[blwq]*_" $IDEAL
grep "^seta[blwq]*_" $IDEAL
grep "^setae[blwq]*_" $IDEAL
grep "^setb[blwq]*_" $IDEAL
grep "^setbe[blwq]*_" $IDEAL
grep "^setc[blwq]*_" $IDEAL
grep "^sete[blwq]*_" $IDEAL
grep "^setg[blwq]*_" $IDEAL
grep "^setge[blwq]*_" $IDEAL
grep "^setl[blwq]*_" $IDEAL
grep "^setle[blwq]*_" $IDEAL
grep "^setna[blwq]*_" $IDEAL
grep "^setnae[blwq]*_" $IDEAL
grep "^setnb[blwq]*_" $IDEAL
grep "^setnbe[blwq]*_" $IDEAL
grep "^setnc[blwq]*_" $IDEAL
grep "^setne[blwq]*_" $IDEAL
grep "^setng[blwq]*_" $IDEAL
grep "^setnge[blwq]*_" $IDEAL
grep "^setnl[blwq]*_" $IDEAL
grep "^setnle[blwq]*_" $IDEAL
grep "^setno[blwq]*_" $IDEAL
grep "^setnp[blwq]*_" $IDEAL
grep "^setns[blwq]*_" $IDEAL
grep "^setnz[blwq]*_" $IDEAL
grep "^seto[blwq]*_" $IDEAL
grep "^setp[blwq]*_" $IDEAL
grep "^setpo[blwq]*_" $IDEAL
grep "^sets[blwq]*_" $IDEAL
grep "^setz[blwq]*_" $IDEAL
grep "^shl[blwq]*_" $IDEAL
grep "^shr[blwq]*_" $IDEAL
grep "^shrx[blwq]*_" $IDEAL
grep "^sqrtpd[blwq]*_" $IDEAL
grep "^sqrtps[blwq]*_" $IDEAL
grep "^sqrtsd[blwq]*_" $IDEAL
grep "^sqrtss[blwq]*_" $IDEAL
grep "^stc" $IDEAL
grep "^sub[blwq]*_" $IDEAL
grep "^subpd[blwq]*_" $IDEAL
grep "^subps[blwq]*_" $IDEAL
grep "^subsd[blwq]*_" $IDEAL
grep "^subss[blwq]*_" $IDEAL
grep "^support[blwq]*_" $IDEAL
grep "^tzcnt[blwq]*_" $IDEAL
grep "^unpckhpd[blwq]*_" $IDEAL
grep "^unpckhps[blwq]*_" $IDEAL
grep "^unpcklpd[blwq]*_" $IDEAL
grep "^unpcklps[blwq]*_" $IDEAL
grep "^vaddpd[blwq]*_" $IDEAL
grep "^vaddsd[blwq]*_" $IDEAL
grep "^vaddss[blwq]*_" $IDEAL
grep "^vaddsubpd[blwq]*_" $IDEAL
grep "^vaddsubps[blwq]*_" $IDEAL
grep "^vandnpd[blwq]*_" $IDEAL
grep "^vandnps[blwq]*_" $IDEAL
grep "^vandpd[blwq]*_" $IDEAL
grep "^vandps[blwq]*_" $IDEAL
grep "^vbroadcastsd[blwq]*_" $IDEAL
grep "^vbroadcastss[blwq]*_" $IDEAL
grep "^vcvtdq2pd[blwq]*_" $IDEAL
grep "^vcvtdq2ps[blwq]*_" $IDEAL
grep "^vcvtpd2ps[blwq]*_" $IDEAL
grep "^vcvtps2dq[blwq]*_" $IDEAL
grep "^vcvtps2pd[blwq]*_" $IDEAL
grep "^vcvtsd2si[blwq]*_" $IDEAL
grep "^vcvtsd2ss[blwq]*_" $IDEAL
grep "^vcvtss2sd[blwq]*_" $IDEAL
grep "^vcvtss2si[blwq]*_" $IDEAL
grep "^vcvttpd2dq[blwq]*_" $IDEAL
grep "^vcvttps2dq[blwq]*_" $IDEAL
grep "^vcvttsd2si[blwq]*_" $IDEAL
grep "^vcvttss2si[blwq]*_" $IDEAL
grep "^vdivpd[blwq]*_" $IDEAL
grep "^vdivsd[blwq]*_" $IDEAL
grep "^vdivss[blwq]*_" $IDEAL
grep "^vfmadd132ps[blwq]*_" $IDEAL
grep "^vfmadd132sd[blwq]*_" $IDEAL
grep "^vfmadd132ss[blwq]*_" $IDEAL
grep "^vfmadd213ps[blwq]*_" $IDEAL
grep "^vfmadd213sd[blwq]*_" $IDEAL
grep "^vfmadd213ss[blwq]*_" $IDEAL
grep "^vfmadd231ps[blwq]*_" $IDEAL
grep "^vfmadd231sd[blwq]*_" $IDEAL
grep "^vfmadd231ss[blwq]*_" $IDEAL
grep "^vfmaddsub132pd[blwq]*_" $IDEAL
grep "^vfmaddsub132ps[blwq]*_" $IDEAL
grep "^vfmaddsub213pd[blwq]*_" $IDEAL
grep "^vfmaddsub213ps[blwq]*_" $IDEAL
grep "^vfmaddsub231pd[blwq]*_" $IDEAL
grep "^vfmaddsub231ps[blwq]*_" $IDEAL
grep "^vfmsub132ps[blwq]*_" $IDEAL
grep "^vfmsub132sd[blwq]*_" $IDEAL
grep "^vfmsub132ss[blwq]*_" $IDEAL
grep "^vfmsub213pd[blwq]*_" $IDEAL
grep "^vfmsub213ps[blwq]*_" $IDEAL
grep "^vfmsub213sd[blwq]*_" $IDEAL
grep "^vfmsub231pd[blwq]*_" $IDEAL
grep "^vfmsub231ps[blwq]*_" $IDEAL
grep "^vfmsub231sd[blwq]*_" $IDEAL
grep "^vfmsub231ss[blwq]*_" $IDEAL
grep "^vfmsubadd132pd[blwq]*_" $IDEAL
grep "^vfmsubadd132ps[blwq]*_" $IDEAL
grep "^vfmsubadd213pd[blwq]*_" $IDEAL
grep "^vfmsubadd213ps[blwq]*_" $IDEAL
grep "^vfmsubadd231pd[blwq]*_" $IDEAL
grep "^vfmsubadd231ps[blwq]*_" $IDEAL
grep "^vfnmadd132ps[blwq]*_" $IDEAL
grep "^vfnmadd132sd[blwq]*_" $IDEAL
grep "^vfnmadd132ss[blwq]*_" $IDEAL
grep "^vfnmadd213pd[blwq]*_" $IDEAL
grep "^vfnmadd213ps[blwq]*_" $IDEAL
grep "^vfnmadd213sd[blwq]*_" $IDEAL
grep "^vfnmadd213ss[blwq]*_" $IDEAL
grep "^vfnmadd231pd[blwq]*_" $IDEAL
grep "^vfnmadd231ps[blwq]*_" $IDEAL
grep "^vfnmadd231sd[blwq]*_" $IDEAL
grep "^vfnmadd231ss[blwq]*_" $IDEAL
grep "^vfnmsub132pd[blwq]*_" $IDEAL
grep "^vfnmsub132ps[blwq]*_" $IDEAL
grep "^vfnmsub132sd[blwq]*_" $IDEAL
grep "^vfnmsub132ss[blwq]*_" $IDEAL
grep "^vfnmsub213pd[blwq]*_" $IDEAL
grep "^vfnmsub213ps[blwq]*_" $IDEAL
grep "^vfnmsub213sd[blwq]*_" $IDEAL
grep "^vfnmsub213ss[blwq]*_" $IDEAL
grep "^vfnmsub231pd[blwq]*_" $IDEAL
grep "^vfnmsub231ps[blwq]*_" $IDEAL
grep "^vfnmsub231sd[blwq]*_" $IDEAL
grep "^vfnmsub231ss[blwq]*_" $IDEAL
grep "^vhaddpd[blwq]*_" $IDEAL
grep "^vhaddps[blwq]*_" $IDEAL
grep "^vhsubpd[blwq]*_" $IDEAL
grep "^vhsubps[blwq]*_" $IDEAL
grep "^vmaxpd[blwq]*_" $IDEAL
grep "^vmaxps[blwq]*_" $IDEAL
grep "^vmaxsd[blwq]*_" $IDEAL
grep "^vmaxss[blwq]*_" $IDEAL
grep "^vminpd[blwq]*_" $IDEAL
grep "^vminps[blwq]*_" $IDEAL
grep "^vminsd[blwq]*_" $IDEAL
grep "^vminss[blwq]*_" $IDEAL
grep "^vmovapd[blwq]*_" $IDEAL
grep "^vmovaps[blwq]*_" $IDEAL
grep "^vmovddup[blwq]*_" $IDEAL
grep "^vmovdqa[blwq]*_" $IDEAL
grep "^vmovdqu[blwq]*_" $IDEAL
grep "^vmovhlps[blwq]*_" $IDEAL
grep "^vmovlhps[blwq]*_" $IDEAL
grep "^vmovmskpd[blwq]*_" $IDEAL
grep "^vmovq[blwq]*_" $IDEAL
grep "^vmovsd[blwq]*_" $IDEAL
grep "^vmovshdup[blwq]*_" $IDEAL
grep "^vmovsldup[blwq]*_" $IDEAL
grep "^vmovss[blwq]*_" $IDEAL
grep "^vmovupd[blwq]*_" $IDEAL
grep "^vmovups[blwq]*_" $IDEAL
grep "^vmulpd[blwq]*_" $IDEAL
grep "^vmulsd[blwq]*_" $IDEAL
grep "^vmulss[blwq]*_" $IDEAL
grep "^vpaddd[blwq]*_" $IDEAL
grep "^vpaddq[blwq]*_" $IDEAL
grep "^vpandn[blwq]*_" $IDEAL
grep "^vpbroadcastb[blwq]*_" $IDEAL
grep "^vpbroadcastd[blwq]*_" $IDEAL
grep "^vpbroadcastq[blwq]*_" $IDEAL
grep "^vpbroadcastw[blwq]*_" $IDEAL
grep "^vpmovsxbd[blwq]*_" $IDEAL
grep "^vpmovsxbq[blwq]*_" $IDEAL
grep "^vpmovsxdq[blwq]*_" $IDEAL
grep "^vpmovsxwd[blwq]*_" $IDEAL
grep "^vpmovzxbd[blwq]*_" $IDEAL
grep "^vpmovzxdq[blwq]*_" $IDEAL
grep "^vpmovzxwd[blwq]*_" $IDEAL
grep "^vpmovzxwq[blwq]*_" $IDEAL
grep "^vpor[blwq]*_" $IDEAL
grep "^vpsubd[blwq]*_" $IDEAL
grep "^vpsubq[blwq]*_" $IDEAL
grep "^vpunpckhdq[blwq]*_" $IDEAL
grep "^vpunpckhqdq[blwq]*_" $IDEAL
grep "^vpunpckhwd[blwq]*_" $IDEAL
grep "^vpunpcklqdq[blwq]*_" $IDEAL
grep "^vpunpcklwd[blwq]*_" $IDEAL
grep "^vrcpps[blwq]*_" $IDEAL
grep "^vrcpss[blwq]*_" $IDEAL
grep "^vrsqrtss[blwq]*_" $IDEAL
grep "^vsqrtps[blwq]*_" $IDEAL
grep "^vsubpd[blwq]*_" $IDEAL
grep "^vsubsd[blwq]*_" $IDEAL
grep "^vsubss[blwq]*_" $IDEAL
grep "^vunpckhpd[blwq]*_" $IDEAL
grep "^vunpcklps[blwq]*_" $IDEAL
grep "^vxorpd[blwq]*_" $IDEAL
grep "^vxorps[blwq]*_" $IDEAL
grep "^vzeroall" $IDEAL
grep "^xadd[blwq_]*" $IDEAL
grep "^xchg[blwq_]*" $IDEAL
grep "^xor[blwq_]" $IDEAL
grep "^xorpd[blwq_]*" $IDEAL
grep "^xorps[blwq_]*" $IDEAL
grep "^blsmsk[blwq]*_" $IDEAL
grep "^cdq[blwq]*_" $IDEAL
grep "^cmovnbe[blwq]*_" $IDEAL
grep "^cmovpe[blwq]*_" $IDEAL
grep "^cvtsd2ss[blwq]*_" $IDEAL
grep "^cvtss2sd[blwq]*_" $IDEAL
grep "^movapd[blwq]*_" $IDEAL
grep "^movaps[blwq]*_" $IDEAL
grep "^movddup[blwq]*_" $IDEAL
grep "^movdqa[blwq]*_" $IDEAL
grep "^movdqu[blwq]*_" $IDEAL
grep "^movlhps[blwq]*_" $IDEAL
grep "^movsd[blwq]*_" $IDEAL
grep "^movss[blwq]*_" $IDEAL
grep "^movsx[blwq]*_" $IDEAL
grep "^movupd[blwq]*_" $IDEAL
grep "^movups[blwq]*_" $IDEAL
grep "^pmovzxbq[blwq]*_" $IDEAL
grep "^pmovzxwd[blwq]*_" $IDEAL
grep "^setpe[blwq]*_" $IDEAL
grep "^shlx[blwq]*_" $IDEAL
grep "^test[blwq]*_" $IDEAL
grep "^vaddps[blwq]*_" $IDEAL
grep "^vcvtpd2dq[blwq]*_" $IDEAL
grep "^vcvtsi2sd[blwq]*_" $IDEAL
grep "^vcvtsi2ss[blwq]*_" $IDEAL
grep "^vdivps[blwq]*_" $IDEAL
grep "^vfmadd132pd[blwq]*_" $IDEAL
grep "^vfmadd213pd[blwq]*_" $IDEAL
grep "^vfmadd231pd[blwq]*_" $IDEAL
grep "^vfmsub132pd[blwq]*_" $IDEAL
grep "^vfmsub213ss[blwq]*_" $IDEAL
grep "^vfnmadd132pd[blwq]*_" $IDEAL
grep "^vmovd[blwq]*_" $IDEAL
grep "^vmovmskps[blwq]*_" $IDEAL
grep "^vmovmskps.swp[blwq]*_" $IDEAL
grep "^vmulps[blwq]*_" $IDEAL
grep "^vorpd[blwq]*_" $IDEAL
grep "^vorps[blwq]*_" $IDEAL
grep "^vpand[blwq]*_" $IDEAL
grep "^vphaddd[blwq]*_" $IDEAL
grep "^vphsubd[blwq]*_" $IDEAL
grep "^vpmovsxwq[blwq]*_" $IDEAL
grep "^vpmovzxbq[blwq]*_" $IDEAL
grep "^vpunpckldq[blwq]*_" $IDEAL
grep "^vpxor[blwq]*_" $IDEAL
grep "^vrsqrtps[blwq]*_" $IDEAL
grep "^vsqrtpd[blwq]*_" $IDEAL
grep "^vsqrtsd[blwq]*_" $IDEAL
grep "^vsqrtss[blwq]*_" $IDEAL
grep "^vsubps[blwq]*_" $IDEAL
grep "^vunpckhps[blwq]*_" $IDEAL
grep "^vunpcklpd[blwq]*_" $IDEAL
